name: buybookapp
description: "The buybook app"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.16.0  
  firebase_auth: 
  cloud_firestore: 

  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  cupertino_icons: ^1.0.8

  user_repo: 
    path: packages/user_repo

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

